### ISSUE TITLE
/Projects -Login to Create Button Overlapping

### ISSUE THREAD

**Issue by Debangan202Ok** [Abbhiishek/codecommunitymusic-client#14] opened 2023-09-08 08:18 UTC
### On small devices, the text 'Login to Create Project' button is overlapping in the Projects section.
- page link given below:
```
https://codecommunitymusic.vercel.app/project
```
<img src="https://github.com/Abbhiishek/codecommunitymusic-client/assets/98002712/73052082-0245-4aa7-8754-5a3fbcf99a9a" alt="codecommunitymusic vercel app_project" width="480" height="768">

**Comment by Abbhiishek** [comment] 2023-09-17 07:46
Thanks for poinitng out @Debangan202Ok 

Do you want to fix this up ?

**Comment by Debangan202Ok** [comment] 2023-09-17 08:49
@Abbhiishek sure! I will fix this.😊

**Comment by Debangan202Ok** [comment] 2023-09-20 17:07
Hello @Abbhiishek,

I'm currently facing an issue with the button UI after cloning the repository and attempting to run it locally. Unfortunately, I'm encountering an 'unauthorized' error, and this prevents me from previewing the UI and addressing the button-related problem. Could you please take a look at this issue and provide guidance on how to resolve it?

**Comment by Abbhiishek** [comment] 2023-09-21 06:11
Hello @Debangan202Ok this is happening cause this is a client part project, we have a backend service too.

**Comment by Abbhiishek** [comment] 2023-09-21 06:11
try to find the component where this issue is happening..

**Comment by Debangan202Ok** [comment] 2023-09-21 06:41
> Hello @Debangan202Ok this is happening cause this is a client part project, we have a backend service too.

Hi @Abbhiishek, I've already cloned the backend services along with their necessary modules that are listed in the requirements.txt file, but the backend service is still throwing an error.

Error in terminal:
```
Watching for file changes with StatReloader
Performing system checks...

System check identified some issues:

WARNINGS:
?: (staticfiles.W004) The directory '/workspaces/codecommunitymusic-server/static' in the STATICFILES_DIRS setting does not exist.
app.User.followers: (fields.W345) related_name has no effect on ManyToManyField with a symmetrical relationship, e.g. to "self".
app.User.following: (fields.W345) related_name has no effect on ManyToManyField with a symmetrical relationship, e.g. to "self".

System check identified 3 issues (0 silenced).
September 21, 2023 - 06:39:08
Django version 4.0, using settings 'core.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Unauthorized: /
[21/Sep/2023 06:39:15] "GET / HTTP/1.1" 401 66
Unauthorized: /favicon.ico
[21/Sep/2023 06:39:15] "GET /favicon.ico HTTP/1.1" 401 66

```

**Comment by Debangan202Ok** [comment] 2023-09-21 06:55
> try to find the component where this issue is happening..

I found the component. It's in `codecommunitymusic-client/app/projects/Projects.tsx`.
here is the component link: [Projects.tsx](https://github.com/Abbhiishek/codecommunitymusic-client/blob/main/app/project/Projects.tsx) line no. 70-76
code snippet:
```
                                <Link href={`/login`} legacyBehavior>
                                    <Button
                                        variant={'secondary'}
                                        className="inline-block">
                                        Login to Create Project
                                    </Button>
                                </Link>
```

**Comment by Abbhiishek** [comment] 2023-09-21 07:19
Great 

try to add these variables in env file and restart the app

```
APP_URL=http://localhost:3000/
NEXT_PUBLIC_BACKEND_URL=http://127.0.0.1:8000/
BACKEND_URL=http://127.0.0.1:8000/
```

make sure your backend is also running

**Comment by Abbhiishek** [comment] 2023-09-21 07:20
However the problem is with the css styling of the component still you can try out the stuffs :)

**Comment by Debangan202Ok** [comment] 2023-09-21 08:47
> However the problem is with the css styling of the component still you can try out the stuffs :)

Yes, I agree. However, I still want to explore the whole project and make some more contributions. ^__^

**Comment by Abbhiishek** [comment] 2023-09-21 13:03
sure @Debangan202Ok 

can you tweek the styling of the component so that its fits the text or else we can use icons to denotes the action? We are using [Lucide icons](https://lucide.dev/icons), have a look.

**Comment by Debangan202Ok** [comment] 2023-09-21 14:31
> sure @Debangan202Ok
> 
> can you tweek the styling of the component so that its fits the text or else we can use icons to denotes the action? We are using [Lucide icons](https://lucide.dev/icons), have a look.
yes @Abbhiishek 
Please review the changes I made in PR #16

**Comment by Abbhiishek** [comment] 2023-09-21 16:50
Thanks @Debangan202Ok for contributing to the project.

PR Merged ✅

**Comment by Abbhiishek** [comment] 2023-09-30 06:31
Hey @Debangan202Ok

I am opening this again can you add up your details in the mentioned file :

config/contributors.ts

Make sure you follow the type defination as follow :

interface IContributors {
    name: string;
    role: string;
    issueLink: string;
    prLink: string;
    githubAccountUrl: string;
    rewviewWords: string;
}
Happy Hacking 🙌

**Comment by Debangan202Ok** [comment] 2023-09-30 10:56
Hi, @Abbhiishek 
`interface IContributors  {...}` not exist in the 'types' directory? Should I create an IContributor.tsx file?
I'm saying this because `config/contributors.ts` have:
```
export const Contributors = [
    {
        name: 'Abhishek kushwaha',
        role: 'Full Stack Developer',
        issueLink: "https://github.com/Abbhiishek/codecommunitymusic-client/issues/",
        prLink: "demo-data",
        githubAccountUrl: "https://github.com/Abbhiishek",
        rewviewWords: "hola! Happy Hacking 2023"
    }
             
] as const;
```

**Comment by Debangan202Ok** [comment] 2023-09-30 11:21
@Abbhiishek
After editing `config\contributors.ts` 
```
interface IContributors {
    name: string;
    role: string;
    issueLink: string;
    prLink: string;
    githubAccountUrl: string;
    rewviewWords: string;
}

export const Contributors : IContributors[] = [
    {
        name: 'Abhishek kushwaha',
        role: 'Full Stack Developer',
        issueLink: "https://github.com/Abbhiishek/codecommunitymusic-client/issues/",
        prLink: "demo-data",
        githubAccountUrl: "https://github.com/Abbhiishek",
        rewviewWords: "hola! Happy Hacking 2023"
    },
    {
        name: 'Debangan Paul Chowdhury',
        role: 'Full Stack Developer',
        issueLink: "https://github.com/Abbhiishek/codecommunitymusic-client/issues/14",
        prLink: "https://github.com/Abbhiishek/codecommunitymusic-client/pull/16",
        githubAccountUrl: "https://github.com/Debangan202Ok",
        rewviewWords: "hola! Happy Hacking 2023"
    }
];
```
Please tell me if I did something wrong.

**Comment by Abbhiishek** [comment] 2023-09-30 13:19
Can you add a new file in types folder with the type declaration.

File : `types/Contributor.ts`
Type declaration: 

```ts
interface IContributors {
    name: string;
    role: string;
    issueLink: string;
    prLink: string;
    githubAccountUrl: string;
    rewviewWords: string;
}
```

Rest LTGM 🙌

**Comment by Debangan202Ok** [comment] 2023-09-30 16:07
> Can you add a new file in types folder with the type declaration.
> 
> File : `types/Contributor.ts` Type declaration:
> 
> ```ts
> interface IContributors {
>     name: string;
>     role: string;
>     issueLink: string;
>     prLink: string;
>     githubAccountUrl: string;
>     rewviewWords: string;
> }
> ```
> 
> Rest LTGM 🙌

Please check Pr #24

**Comment by Abbhiishek** [comment] 2023-10-03 13:44
Closing this issue as it was resolved.

Also the contributor details where added to site: https://codecommunitymusic.vercel.app/contributors

**Closed by Abbhiishek** 2023-10-03 13:44 UTC
Labels: good first issue
